name: 🐞 Report a bug
description: Create a report to help us fix something that is not working correctly
title: "Bug: <Brief description of the bug>"
labels: ["Status: Needs Review", "Type: Bug"]
assignees:
  - nil
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing your ideas to make our project better!

        To help us understand and evaluate your suggestion in a reasonable amount of time, please provide detailed information below.

        If you have any questions or are unsure about anything, don't be afraid to ask! The maintainers are here to help.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: "Please confirm the following prequisites are met:"
      options:
        - label: I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have searched the existing issues to ensure this bug hasn't been reported before (please have a look through our [open issues list](https://github.com/TheOdinProject/javascript-exercises/issues) to make sure)
          required: true
        - label: "The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Exercises: File type incorrect for all test files`"
          required: true
        - label: (Optional) I am interested in working on this issue and would like to be assigned to it
          required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Clearly describe the bug. Include any screenshots that may help show the bug in action.
    validations:
      required: true

  - type: textarea
    id: bug-reproducement
    attributes:
      label: How to reproduce the bug
      description: "List what steps one might need to take in order to reproduce this bug"
      placeholder: |
        1. Log in
        2. Visit a lesson page
        3. Click the complete button
        4. The complete button does not update
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A brief description of what you expected to happen
      placeholder: |
        1. Log in
        2. Visit a lesson page
        3. Click the complete button
        4. The complete button updates correctly
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: iPhone6
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: iOS
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser and its version
      placeholder: Chrome 122
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: (Optional) Additional Comments
      description: Provide any extra information that might be helpful, such as links to Discorddiscussions, screenshots, or other relevant details.
      placeholder: We ❤️ open source
    validations:
      required: false
