name: Tests
on:
  pull_request:
    paths:
      - 'package*.json'
      - '**/solution/*.js'

jobs:
  tests:
    name: Run solution tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
      - run: npm install
      - run: npm run test -- solution
